// <auto-generated />
namespace GenteFit.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class InicialLimpia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InicialLimpia));
        
        string IMigrationMetadata.Id
        {
            get { return "202512101733360_InicialLimpia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
